### ISSUE TITLE
Q/A - Vérifier les ano

### ISSUE THREAD

**Issue by jguihot** [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation#100]
## Problèmes rencontrés

              Il y a des choses à corriger dans le Q/A : https://ansforge.github.io/IG-fhir-medicosocial-suivi-decisions-orientation/ig/presta-98/qa.html
Mettre le package NOS dans les dépendances

_Originally posted by @nriss in https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/issues/49#issuecomment-1892381146_

**Comment by jguihot** [comment]
Plusieurs ano remontées:
- ContenuDossier => ne pourra être corrigé que lors de la restructuration de la spécification CDA (issue #54) => OK
- index : pdf modifié dans la PR #80 => OK
- flux 5 : corrigé dans la PR #94 => OK
- st_flux1 : à étudier
- Ressource Consent : cette valeur avait déjà été modifiée pour faire suite à une ano remontée sur FhirValidator disant que la valeur Patient Consent était outdated => à étudier
- sdo_task => à étudier
- ValueSet => Reference aux NOS faite via la PR #87

**Comment by jguihot** [comment]
@TristanKEREVAL , je veux bien ton input sur les points identifiés que je n'ai pas coché

**Comment by jguihot** [comment]
@nriss , nous avons un soucis avec une des erreurs relevées dans le Q/A.
Pour la ressource Consent, nous avions initialement utilisé la valeur "Patient Consent", mais, lors de la validation de notre exemple dans FhirValidator, nous avions remonté une erreur nous disant que cette valeur n'était pas prise en compte. Après vérification dans la LOINC (https://loinc.org/59284-0/), nous avions effectivement constaté que le display avait évolué pour supprimée "Patient", devenant donc Consent. Nous avions donc fait la modification en conséquence dans la SD et dans l'exemple.
Mais ô surprise, voilà que l'erreur inverse se présente. Le "Consent" étant refusé, un "Patient Consent" étant attendu ! La LOINC précise pourtant toujours que le short name est "Consent", et le long name "Consent Document".
Nous ne savons donc pas quoi faire de cette anomalie, la doc FHIR n'a a priori pas suivi l'évolution de la LOINC. Un avis sur la question ?

**Comment by nriss** [comment]
Peut être que c'est un problème au niveau de la validation des codes LOINC ? Il y a bien écrit "Patient Consent" dans le CodeSystem donc je propose de rester dessus https://www.hl7.org/fhir/R4/valueset-consent-category.html

Peux-tu mettre un petit commentaire dans le fichier fsh pour indiquer le problème ? P-ê mettre un lien vers l'issue aussi

**Comment by jguihot** [comment]
@nriss , tu pointes ici la doc FHIR, qui indique effectivement Patient Consent. Mais si tu suis le lien LOINC mentionné dans cette doc, tu verras que Patient Consent n'existe pas, le display a évolué et la doc FHIR n'a pas suivi
![image](https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/assets/135017301/bc8f35e8-eacd-4324-af9b-99a218da6fe0)

**Comment by TristanKEREVAL** [comment]
Quand on met "Patient Consent " on a : 
![image](https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/assets/122813625/536151df-ea0b-4c7f-85bc-600180d47a32)
Quand on met "Consent" ou "Consent Document" on a : 
![image](https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/assets/122813625/5cd1b705-97c8-42ef-83a9-2e18e47210c8)

**Comment by nriss** [comment]
Et en R5, ça reste Patient Consent ! https://www.hl7.org/fhir/valueset-consent-category.html

Etant donné que l'erreur est insoluble (incohérence entre LOINC et le ValueSet FHIR), je propose d'ignorer l'erreur !

Si ça vous dit, vous pouvez poster l'issue sur le jira d'HL7 :)

**Comment by jguihot** [comment]
Pour les anomalies liées à la StructureDef, correction à prévoir (issue #108)

**Comment by TristanKEREVAL** [comment]
Ticket JIRA créé : https://jira.hl7.org/browse/FHIR-44625

**Comment by jguihot** [comment]
nouvelle issue créée pour suivi de l'issue JIRA => issue #133
