### ISSUE TITLE
Consent - incohérence référence à la ressource SDOTask

### ISSUE THREAD

**Issue by jguihot** [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation#119]
## Description du problème

![Image](https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/assets/135017301/ce822f03-8a20-40fd-a6a9-10159adacda6)

La référence à la structureDef SdoTask n'a pas lieu d'être

## Fichier•s concerné•s
ESMSConsnet.json

## Solution proposée
Corriger le fichier

**Comment by jguihot** [comment]
@nriss , serais-tu inspiré par cette probématique ? J'ai du mal à voir d'où vient la référence SDOTask, elle n'est pas dans le code...

**Comment by nriss** [comment]
Ici ? Je ne comprends pas le problème
https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/blob/cba35ba48c40520b7b0948b77d98ff5b90c18824/input/FHIR/StructureDefinition-esms-consent.json#L90

**Comment by jguihot** [comment]
Le problème c'est que je regarde l'exemple au lieu de la structureDef... Forcément...
