### ISSUE TITLE
LEs documents pdf sont erronés

### ISSUE THREAD

**Issue by nriss** [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation#12]
<img width="970" alt="image" src="https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/assets/48218773/a74509a8-f1cd-4056-9834-526537e888f5">

- Typo ')' à la fin
- Même document 3 fois
- Commence par 2.

**Comment by jguihot** [comment]
Les PDF ne sont pas erronés. Il s'agit d'un extrait des spécifications techniques pdf actuellement publiées (d'où le démarrage au chapitre 2). 3 fois le même PDF parce que nous n'arrivons pas à pointer vers un chapitre du PDF.
Pour rappel, il avait été convenu de mettre en place l'IG dans le but premier de faire passer nos validateurs par matchbox.
La première version de cet Ig devait donc être centré principalement sur la partie FHIR. Il avait été convenu, que, au vu des échéances serrées, et de l'absence de maîtrise de la gestion de données CDA en IG, nous conserverions la partie CDA en pdf.

La prochaine version de cet IG intègrera les tableaux CDA directement dans l'IG. Nous nous affranchirons donc des PDF.

En revanche la typo, bien vu
