### ISSUE TITLE
RC - Incohérence entre nom de slice et valeur du discriminateur

### ISSUE THREAD

**Issue by TristanKEREVAL** [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation#152]
## Description du problème
Le slicing se fait sur un champ texte qu'on a assigné à chaque slice. Ce champ fixe est identique au nom de la slice pour toutes sauf pour "temporaliteAccueuil"
 : 
"id": "Task.input:temporaliteAcceuil",
				"path": "Task.input",
				"sliceName": "temporaliteAcceuil",
				"max": "1",
				"short": "Permet de définir la fréquence d'accueil lors d'une prise en charge en ESMS"
			},
			{
				"id": "Task.input:temporaliteAcceuil.type.text",
				"path": "Task.input.type.text",
				"fixedString": "**temporaliteAccueil**"
## Fichier•s concerné•s
/StructureDefinition-sdo-task.json

## Solution proposée
Corriger la faute dans la "fixedString" de la slice

**Comment by nriss** [comment]
Hello Tristan! Merci pour l'issue

Je vous invite à utiliser le permalink permet d'éviter de chercher le fichier

<img width="1283" alt="image" src="https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/assets/48218773/f7f4f7c9-85ef-482b-b80b-599594cc4d5f">

https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/blob/fc19aa6d1152580e26de2a32e8f30de8c633bdab/input/FHIR/StructureDefinition-sdo-task.json#L289


De plus, on est pas très conforme à FHIR là, le champs text doit être utilisé pour avoir une représentation textuelle du contexte et non pas de la slice/du JDV associé.

<img width="664" alt="image" src="https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/assets/48218773/832709d2-7f08-4a61-9e57-5daa9da6215d">

Je vous invite plutôt à créer une extension avec un code fixed (+VS + CS)

**Comment by jguihot** [comment]
@nriss , je trace ta remarque dans une nouvelle issue pour étudier le remaniement de cette SD. Dans l'immédiat nous traitons la correction orthographique.
