### ISSUE TITLE
 ESMSDocumentReference

### ISSUE THREAD

**Issue by SEBELIN** [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation#169]
## Description du problème
Dans la description du type fermer les guillemets: Display = **« Evaluation note**

et mettre guillemets Display = **"Admission request Document."**

De plus il faudrait rajouter la ref à la nomenclature LOINC
Si la ressource contient le document CDA portant les données de individu et la décision : Code = « 57830-2 » de la **nomenclature LOINC** docTypeCodes, Display = Admission request Document. 
Si la ressource contient le document CDA portant l'évaluation : Code = « 51848-0 » de la **nomenclature LOINC** docTypeCodes, Display = « Evaluation note » 

## Fichier•s concerné•s
[ESMSDocumentReference.fsh]

**Comment by jguihot** [comment]
@SEBELIN , je clôture cette issue.
1 / Dans la future version des spécifications, seuls le code sera mentionné, afin de ne pas être affecté par les modifications des displayname.
2/ la nomenclature LOINC est déjà citée dans les ressources, il s'agit du binding d'origine de la ressource, que nous n'avons pas touché. Nous imposons simplement le code à utiliser dans ce value Set:


![Image](https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/assets/135017301/b32d5869-46c2-41a2-a251-a3b4087c275d)
