### ISSUE TITLE
séparer les annexes de "Autres ressources"

### ISSUE THREAD

**Issue by jguihot** [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation#17]
Les annexes sont directement liées au volet et importantes à la mise en place des spécifications techniques. A mettre en évidence dans un onglet dédié

**Comment by TristanKEREVAL** [comment]
Ajouter l'annexe Diagramme de Séquence SI-MDPH / SI-SDO / SI-ESMS

**Comment by jguihot** [comment]
Annexe OID à retravailler

**Comment by jguihot** [comment]
problème d'affichage et de lien cliquable sur l'annexe nomenclature

**Comment by jguihot** [comment]
Suppression reliquat nomenclatures sur page OID (commit #94)
