### ISSUE TITLE
RC - Synthèse des ressources

### ISSUE THREAD

**Issue by jguihot** [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation#180]
## Description du problème

Sur demande de l'ANS, une page "liste_profils" a été créé pour suplanter la page "artifacts summary" et permettre de séparer les profils génériques et les profils applicatifs. 
Pb : perte de l'automatisation de la complétion de la page des ressources FHIR + risque de divergence avec les actuelles ressources

## Fichier•s concerné•s
liste_profils.md
index.md
artifacts

## Solution proposée
préférer séparer les profils sur le tableau de la page d'accueil. Et remettre la page artifacts summary en lieu et place de la page "liste_profils"

**Comment by jguihot** [comment]
@nriss , nous avions modifié à ta demande la synthèse des ressources de conformité pour pouvoir les catégoriser en profils vs génériques. Avec les créations de JDV et de codeSystem qui ont été récemment fait, je trouverais plus pertinent de revenir à la page "artifacts" classique qui se met à jour automatiquement. Les tableaux présents sur la page d'accueil devrait suffire à spécifier quelle ressource est utilisée dans quelle cadre. Qu'en penses-tu ?

@SEBELIN , pour info

**Comment by TristanKEREVAL** [comment]
Nécessite la modification de la description des StructureDefinition pour avoir des données "discriminantes" entre les 2 catégories de StructureDefinition. 
On peut reprendre la même définition qu'actuellement, à savoir une description qui commence par : "Profil générique" ou "Profil applicatif".
Ça serait ok pour vous ? @nriss @SEBELIN @jguihot

**Comment by nriss** [comment]
Ok pour moi!
Par contre en voyant la page, on ne comprend pas trop pourquoi des profils SDO, ESMS sont génériques, et dans l'applicatif, on a aussi SDO, ESMS

En gros ma question : en quoi est-ce que c'est générique si c'est spécifique à SDO ? Je pense qu'il y a quelque chose à préciser pour l'utilisateur ici

**Comment by jguihot** [comment]
Alors, initialement on a séparé ça comme ça à ta demande, mais nous l'avons peut être ma comprise ! Nous avons placé dans les profils génériques tous les profils qui sont sur-profilés si besoin.
Du coup tu mettrais également les ressources SDO dans les profils spécifiques ? Et on hériterait d'un profil spécifique ?
Les seuls profils génériques que nous conserverions seraient SDO_Task parce qu'il est utilisé sur les deux volets et ESMS_Consent parce que j'imagine mal comment nous pourrions le sur-contraindre.
A noter qu'aucun de ces profils n'a été créé avec vision d'ensemble sur les volets médico-social, je ne suis pas certaine qu'aucun de ces profils puisse être considéré comme générique. Le cadre d'urbanisation du médico-social est encore en cours de construction. La vision d'ensemble n'est pas pour tout de suite.

**Comment by nriss** [comment]
Ok! Très clair, donc les termes générique et applicatif ne sont pas bons ici. Ce sont finalement tous des profils applicatifs qui seront développés, il y en a aucun qui est réellement 'générique' qui sert juste de socle de base, on est d'accord ?

Dans ce cas, il est peut être mieux de créer des catégories SDO et ESMS peut être ? Et utiliser effectivement une requête SQL pour séparer SDO et ESMS ? Mais dans le cas de SDOTask qui est utilisé dans SDO ET dans ESMS, pourquoi celui-ci s'appelle SDOTask du coup ?

Désolé de revenir sur ma parole, je pense qu'il faut une vision d'ensemble des ressources profilées et de leur usage pour répondre à cette problématique que je n'ai pas, qu'en pensez-vous ?

**Comment by jguihot** [comment]
Ah mon sens, ils peuvent effectivement difficilement être considérés comme des profils génériques, dans la mesure où ils ont été pensés pour un besoin bien précis et pas pour répondre à une problématique médico-sociale plus large. @SEBELIN , qu'en penses-tu ?

Idem pour le nom des ressources. Elles ont été pensées initialement pour le volet SDO. Le volet ESMS est arrivé par la suite et pouvait s'appuyer sur certaines ressources existantes coté SDO, que nous avons donc réemployées. Nous avions suggéré une modification de nom, mais à l'époque ça n'avait pas été validé coté ANS car les éditeurs étaient trop avancés dans leurs développements du volet SI-SDO. En soit, ça n'est pas totalement incorrect de les appeler SDO, puisque les deux volets SI-SDO et SI-ESMS sont regroupés dans le suivi des orientations (SDO), d'où le nom de cet IG, sdo. Il n'y a que la ressource SDODocumentReference qui n'est utilisée que dans un volet, et encore, elle est profilée, donc implicitement utilisée dans les 2 volets.

C'est une problématique sur laquelle Eric travaille beaucoup, orienter la CNSA vers une réflexion globale et non centrée cas d'usage, afin de créer des objets génériques pour un profilage suivant cas d'usage. Ce fonctionnement commence à prendre forme coté CDA mais nous n'y sommes pas encore coté FHIR, il nous faut travailler encore le sujet.

J'espère t'avoir éclairé un peu sur le contexte et je suis d'accord, difficile de rentrer dans le sujet sans avoir tout l'historique. Nous allons travailler à une alternative à cette présentation et te la ferons valider. Tu nous diras si tu trouves ça plus clair

**Comment by nriss** [comment]
Ca marche, merci ! :)
J'avais eu aussi l'idée de créer deux tableaux SDO et ESMS (générés dynamiquement), quitte à avoir des profils en doublon dans les tableaux, mais à voir si ça a du sens fonctionnellement!

**Comment by jguihot** [comment]
Solution finale : 

- Ressources ESMS dans un tableau distinct avec description "Profil ESMS [...]" si la ressource est spécifique au volet ou "Profil ESMS - SDO [...] si la ressource est utilisée dans les deux volets. Permet de remonter les ressources via requête sur la description : Description like "Profil ESMS%"
- Ressource SDO dans un tableau distinct avec description "Profil SDO [...]" si la ressource est spécifique au volet ou "Profil ESMS - SDO [...] si la ressource est utilisée dans les deux volets. Permet de remonter les ressources via requête sur la description : Description like "%SDO%"

**Comment by TristanKEREVAL** [comment]
Solution finale :

    Ressources ESMS dans un tableau distinct avec description "Profil ESMS [...]" si la ressource est spécifique au volet ou "Profil ESMS - SDO [...] si la ressource est utilisée dans les deux volets. Permet de remonter les ressources via requête sur la description : Description like "Profil ESMS%"
    Ressource SDO dans un tableau distinct avec description "Profil SDO [...]" si la ressource est spécifique au volet ou "Profil ESMS - SDO [...] si la ressource est utilisée dans les deux volets. Permet de remonter les ressources via requête sur la description : Description like "Profil SDO%" OR Description like "Profil ESMS-%"
