### ISSUE TITLE
Validateur CDA - Ajouter une règle de gestion sur le versionning

### ISSUE THREAD

**Issue by jguihot** [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation#195]
## Description du problème

Ajouter une règle de gestion pour gérer les éléments du versionning : si versionNumber alors setId et relatedDocument obligatoires

## Fichier•s concerné•s
schematron document 
Projet ESMS

**Comment by KerJac35** [comment]
Règle testée et ajoutée dans les templates de document Décision et Evaluation
