### ISSUE TITLE
Securité - Corriger typo

### ISSUE THREAD

**Issue by jguihot** [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation#218]
## Description du problème
              ok :) Typo à corriger

_Originally posted by @nriss in https://github.com/ansforge/IG-fhir-medicosocial-transfert-donnees-dui/pull/127#pullrequestreview-2207166676_

              Et saut de ligne

_Originally posted by @nriss in https://github.com/ansforge/IG-fhir-medicosocial-transfert-donnees-dui/pull/127#discussion_r1696643371_
            
            

## Fichier•s concerné•s
securite.md

**Comment by jguihot** [comment]
@SEBELIN , tu as complètement remanié le texte "sécurité" sur TDDUI, à reprendre à l'identique ?

**Comment by SEBELIN** [comment]
Non ce ne sont pas les mêmes endpoint qui gèrent l'authentification. La logique n'est pas forcement la même. On ne change rien sur le volet ESMS, il reste à référencer le lien vers la spec VT d'authentification.


Agence du Numérique en Santé

Eric SEBELIN



Expert

Tél.



+33158456244



________________________________
De : Jeanne GUIHOT ***@***.***>
Envoyé : vendredi 22 novembre 2024 18:55
À : ansforge/IG-fhir-medicosocial-suivi-decisions-orientation ***@***.***>
Cc : Eric SEBELIN ***@***.***>; Mention ***@***.***>
Objet : Re: [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation] Securité - Corriger typo (Issue #218)


@SEBELIN<https://github.com/SEBELIN> , tu as complètement remanié le texte "sécurité" sur TDDUI, à reprendre à l'identique ?

**Comment by jguihot** [comment]
OK. @Tristan pour prise en compte uniquement des typo du coup
