### ISSUE TITLE
Validateur CDA - reporter les évolutions du volet de structuration minimal sur le document

### ISSUE THREAD

**Issue by jguihot** [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation#220]
## Description du problème
Le volet de structuration minimal a évolué pour gérer les nomenclatures via attribut dans le document et utilisations de variables.
Les nomenclatures civilité et suffix doivent être ajouté dans ce nouvel attribut

## Fichier•s concerné•s
schematron document
Projet ESMS

## Solution proposée
Ajouter les JDV_J245, J_246 dans un attribut extraterminologies sur les 2 documents
Voir projet TDDUI en temple

**Comment by KerJac35** [comment]
Ajout des nomenclatures JDV_J245 et JDV_J246 dans un attribut extraterminologies sur les 2 templates de documents Décision et Evaluation
