### ISSUE TITLE
Ressources de conformité - Perdition d'information métier

### ISSUE THREAD

**Issue by TristanKEREVAL** [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation#24]
## Description du problème
Des informations métiers pouvant s'apparenter à des règles de gestion n'ont pas été transmises lors de la conversion vers l'ig.
Ces informations sont présentes dans la section 3.2.2 de la spec au format PDF.
Comment pourrait on les ajouter à la page descriptive du profil sans passer par des règles de gestion ? On avait déjà essayé de les créer mais sans trop de succès (certaines règles étaient conditionnés par le contenu du document CDA par exemple)

Les descriptions de chacune des ressources (voir tableaux 3.2.2.1, 3.2.2.2 et 3.2.2.3 du document word) sont également à rapatrier dans les structures définition

## Fichier•s concerné•s
https://interop.esante.gouv.fr/ig/fhir/sdo/StructureDefinition-esms-document-reference.html
https://interop.esante.gouv.fr/ig/fhir/sdo/StructureDefinition-sdo-task.html
https://interop.esante.gouv.fr/ig/fhir/sdo/StructureDefinition-sdo-consent.html

[20230817_CISIS-TEC_SPECIFICATIONS_TECHNIQUES_SI-ESMS_v3.1.docx](https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/files/13578683/20230817_CISIS-TEC_SPECIFICATIONS_TECHNIQUES_SI-ESMS_v3.1.docx)

**Comment by TristanKEREVAL** [comment]
Pour la Task on a réussi à créer les règles de gestion, pour le DocumentReference on attend plus d'input car les règles de gestions porterait sur le contenu du document transporté et je ne crois pas que ce soit possible de conditionner sur ces éléments

**Comment by TristanKEREVAL** [comment]
Eléments ajoutés dans les SD Consent, DocumentReference et Task

**Comment by jguihot** [comment]
@TristanKEREVAL , il manque la référence à la table d'association pour les éléments motifUnite et motifESMS : https://mos.esante.gouv.fr/NOS/ASS_A32-StatutMotifPersonnePriseCharge/ASS_A32-StatutMotifPersonnePriseCharge.pdf. 
Binding OK, mais phrase à ajouter pour indiquer que, si le statutUnite ou statutESMS est décrit dans la table d'association, alors le motif à renseigner doit être issu de cette table d'association.

@SEBELIN , le motif est-il obligatoire si le statut renseigné est présent dans la table d'association ?

**Comment by jguihot** [comment]
plusieurs anomalies, voir commentaires dans la PR

**Comment by TristanKEREVAL** [comment]
Ajout d'un "short" sur le motifUnite : 		  "short": "Motifs obligatoires pour certains statut suivant la table : https://mos.esante.gouv.fr/NOS/ASS_A32-StatutMotifPersonnePriseCharge/ASS_A32-StatutMotifPersonnePriseCharge.pdf"

**Comment by jguihot** [comment]
Issues indépendantes créées pour les reliquats à traiter. Présente issue clôturée
