### ISSUE TITLE
digramme de séquence flux 3.1

### ISSUE THREAD

**Issue by SEBELIN** [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation#240]
## Description du problème

Plusieurs modifications à prévoir sur le flux 3.1 : 
- [x] la requête get du diagramme de séquence flux 3.1 est à corriger pour supprimer le "elements=id"
~~- [x] Depuis passage de 1 à 2 étapes, le nom du flux devrait être "consultation" et non plus "recherche" : mettre à jour le titre et la description du flux~~
~~- [x] Le nom du validateur d'URL devrait également passer à "consultation"~~
- [x] la synthèse des flux est à mettre à jour : requête à corriger pour supprimer le "elements=id"
~~- [x] le nom de l'onglet est à mettre à jour~~
~~- [x] le nom du flux est à mettre à jour sur l'annexe diagramme de b-e-b~~
~~- [x] Mettre à jour le nom du validateur dans l'onglet test~~

## Fichier•s concerné•s
flux3.plantuml
~~st_flux3.md~~
synthese_flux.md
~~tests.md~~
~~sushi-config.yaml~~
~~validateur URL~~
~~20240124_DiagrammeSequence_Global.drawio -> versionner le nom du fichier modifié ou supprimer la date du nom~~

**Comment by jguihot** [comment]
Pas de renommage du nom du flux
