### ISSUE TITLE
Exemples - Supprimer les références vers des ressources non existantes dans le volet (author,...)

### ISSUE THREAD

**Issue by jguihot** [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation#25]
## Description du problème
Référence vers des ressources inexistantes dans certains exemples

## Fichier•s concerné•s
DocumentReference (vérifier si éventuellement d'autres)

    "author":[
        {
            "reference":"Practitioner/testReference",
            "display":"Practitioner/Dr Test"
        }

## Solution proposée
Soit supprimer complètement l'auteur soit ne conserver que le display

**Comment by nriss** [comment]
C'est pour les exemples dans les IGs ? 
Le plus important étant que ces exemples miment au mieux la réalité, s'il est demandé de faire des références et non des display, je suis plutôt en faveur d'ignorer les erreurs.

Je propose:
- Soit de rajouter les ressources manquantes à l'IG (idéalement, si possible)
- Soit ignorer les erreurs

**Comment by TristanKEREVAL** [comment]
Yes pour les exemples !  Oui mais si ils miment la réalité, et qu'on fait référence à des ressources qui ne sont jamais créé sur le serveur, alors la création générera des erreurs. La validation passera avec des warning.
Le problème n'est pas d'ajouter les ressources à l'IG, c'est juste qu'on peut pas déterminer l'id qu'il faudra utiliser pour les références car les ressources ne sont pas créée sur le serveur et n'ont donc pas d'id

**Comment by nriss** [comment]
S'il n'y a pas de raison qu'il y ait un auteur renseigné, ok pour l'enlever :)

Donc plus généralement, je dirais : 
- Ne renseigner les références que si ça a du sens au sein de l'IG, et uniquement de la manière dont est prévu l'IG (relative, absolue, display ...)
- Si possible, renseigner un maximum de ressources dans l'IG pour que l'exemple soit au plus proche de ce qui est attendu dans la vraie vie
- Au pire des cas, ignorer les erreurs

**Comment by nriss** [comment]
@TristanKEREVAL, dans quel type de création est-ce que l'id n'est pas déterminé ? Avec un bundle ?

**Comment by TristanKEREVAL** [comment]
Bah par exemple dans notre exemple on avait la référence vers un auteur de la note, sauf que si l'utilisateur pousse notre exemple sur un serveur, et que la ressource représentatn l'auteur de la note n'est pas présente sur el serveur avec le même id que dans notre exemple, alors il aura une erruer. Mais comme dit Jeanne c'est un problème plus globale à tous nos exemples FHIR

**Comment by jguihot** [comment]
@nriss , Tristan a repéré le problème avec des exemples sdo, mais en vérité ça n'est pas vraiment lié à l'IG. C'est une problématique qui est apparue pour les essais Testscript (tu m'arrêtes @TristanKEREVAL si je dis des bêtises)

**Comment by jguihot** [comment]
@TristanKEREVAL , author à supprimer également de l'exemple de Bundle [ESMSBundleResultatRechercheDecisionEvaluation.json](https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/pull/49/files#diff-d78cfff9af120ceb2447412c8f3ca12be49c92e674c34273845dea6866a448e1)

**Comment by jguihot** [comment]
Nécessite également une mise à jour de l'exemple SDODocumentReference
