### ISSUE TITLE
Cas de tests - Evolution à prévoir sur l'utilisation des validateurs d'URL

### ISSUE THREAD

**Issue by jguihot** [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation#269]
## Description du problème

A définir : 
- [x] soit suppression des validateurs d'URL
- [ ] soit passage par HTTPValidator

**Comment by KerJac35** [comment]
Vu avec @SEBELIN le 10/12/2024 : suppression des références vers les validateurs d'URL dans la description et les étapes de tests pour les scénarios 1, 2, 4 et 6.
On part du principe que si les ESMS obtiennent une réponse lors de l'envoi de leurs requêtes vers VT, alors cela signifie qu'elles sont valides.
