### ISSUE TITLE
Supprimer les exemples non passant

### ISSUE THREAD

**Issue by jguihot** [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation#27]
## Description du problème
Les exemples non passant utilisés pour tester les validateurs sont intégrés dans l'IG. Ils ne sont pas clarifiés comme non passants et ajoute juste de la confusion à l'IG

## Fichier•s concerné•s
fichiers "-np"

## Solution proposée
Supprimer les exemples non passant de l'IG. A conserver à coté pour les tests de validateurs

**Comment by jguihot** [comment]
@SEBELIN , peux-tu confirmer que tu est OK avec le raisonnement ?

**Comment by SEBELIN** [comment]
Je valide la solution proposée.
