### ISSUE TITLE
RC - Analyse value fixed post transition FSH

### ISSUE THREAD

**Issue by jguihot** [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation#277]
## Description du problème
Comparer les RC avant et après passage des ressources en FSH pour s'assurer qu'aucune valeur fixed n'a été perdue. Le cas échéant, effectuer la correction

## Fichier•s concerné•s
RC FSH

**Comment by TristanKEREVAL** [comment]
3 différence notée : 
* Task.input:statutESMS 1..1 initialement et 0..1 au passage FSH
* Task.input:typeDroitPrestation 0..1 initialement et 1..1 au passage FSH ->Va être supprimée via #265 
* Consent.status initialement fixée à "active" et cette fixed value a disparue au passage FSH -> Fix via #278

**Comment by jguihot** [comment]
Merci @TristanKEREVAL , très clair !

- Point 1 => Evolution demandée et intégrée dans les specs fonctionnelles et technique. Pas à traiter
![image](https://github.com/user-attachments/assets/d37a5f42-1253-4dbe-ab64-84fe217793c4)

- Point 2 => effectivement suppression en cours. Peut être ignoré

- Point 3 => fixed value manquante. A traiter via l'issue dédiée.

@SEBELIN , pour information
