### ISSUE TITLE
Modifier Diagramme de Séquence SI-MDPH / SI-SDO / SI-ESMS

### ISSUE THREAD

**Issue by TristanKEREVAL** [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation#28]
## Description du problème
Le diagramme tel qu'il est présent dans la spec word est trop grand et large pour un affichage optimal sur une page web.
## Fichier•s concerné•s
Diagramme de Séquence SI-MDPH / SI-SDO / SI-ESMS
![image](https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/assets/122813625/1358df77-e81d-4e33-b63f-650d9f6d57ea)

## Solution proposée
Découper l'image en plusieurs plus petites

**Comment by jguihot** [comment]
Pas de découpage, mais format de l'image travaillé dans le code:
<img src="20240115_DiagrammeSequence_Global.jpg" style="width:100%;height:auto;">
