### ISSUE TITLE
NOS - Remplacer les TRE Sexe et Civilité par des JDV

### ISSUE THREAD

**Issue by jguihot** [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation#29]

**Comment by jguihot** [comment]
Remplacer la TRE_R249 par le JDV_J143 CI-SIS
Impacts : spec et exemple. Validateur à jour

**Comment by SEBELIN** [comment]
Les TRE Civilité et Sexe ont été remplacée par des JDV dans la SFE.
[CISIS-SPECIFICATIONS_FONCTIONNELLES_SI-ESMS_v2.5-sans-marques.pdf](https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/files/14096565/CISIS-SPECIFICATIONS_FONCTIONNELLES_SI-ESMS_v2.5-sans-marques.pdf)
