### ISSUE TITLE
Statuts / Motifs : supprimer les références à des codes précis (inclut suppression flux fonctionnel 6 et renommage flux 5)

### ISSUE THREAD

**Issue by jguihot** [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation#30]
## Description du problème (demande initiale de l'ANS)
Les spécifications techniques font référence à des cas d'usage précis qui sont amenés à évoluer, notamment en terme de codes utilisés. Complexifie les spécifications pour une gestion des flux qui ne diffère pas

## Demande initiale non retenue

Ajouter des précisions concernant la gestion de l'annulation d'une demande et du retour au statut 40 "Notification lue" en cas d'une admission impossible qui ne serait plus entérinée : 
- Mettre à jour la spécification fonctionnelle pour faire apparaitre le cas de l’annulation + compléter  le diagramme de séquence au niveau de la spécification technique pour préciser qu'en cas d'annulation, le statut 49 "Notification annulée" redescendra de VT vers les ESMS via les Flux 5.1 (recherche notifications autres ESMS) et 5.3 (consultation notification autres ESMS)  transmis par les ESMS

- Mettre à jour le cas d’une admission impossible non entérinée au niveau des spécificatios fonctionnelles + compléter le diagramme de séquence en annexe de la spécification technique pour indiquer que VT redescend le statut 40 "Notification lue" uniquement à l'ESMS ayant signalée une admission impossible.

## Fichier•s concerné•s
IG (spec technique FHIR)
Spec fonctionnelles ?
Diagrammes d'activité et de séquences

## Solution proposée et validée par l'ANS

Cas d'usage décrits **uniquement dans les spec fonctionnelles**
Ajouter un statut coté VT pour redescendre le statut "AI non entériné" (DM NOS)
**Supprimer le détail dans les spec techniques**. Supprimer les références à des codes statuts et motifs spécifiques et revenir à un processus générique "suivi des statuts des personnes orientées en ESMS"

**Comment by jguihot** [comment]
@KerJac35 , bien vérifier que les références à des codes ou displayname est supprimé, y compris dans les diagrammes


![Image](https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/assets/135017301/9dc747cb-d501-4410-bde1-4b837ca51b7e)

**Comment by KerJac35** [comment]
La plupart des modifications sur l'IG ont été faites par rapport à cette issue, il reste cependant la correspondance avec les éléments métiers indiqués dans la SFE : 
![Capture](https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/assets/143090247/1b378e7a-f006-4287-9823-1993fc2b10f9)

@SEBELIN Est ce qu'il serait possible de mettre à jour les SFE s'il te plaît au niveau du nom des processus ? On va en avoir besoin pour l'IG

**Comment by jguihot** [comment]
@KerJac35 , supprimer également du diagramme le processus "consultation des autres statuts intermédiaires" qui est également à supprimer. Il s'agit d'une transmission de statut classique

**Comment by jguihot** [comment]
MAJ reliquat de mention du flux 6. + modif nom flux 5
-  correspondance_objet : suppression du flux 6 et modification du nom du flux 5
- synthese_flux : suppression du flux 6
- st_flux5 : suppression codes
- st_flux5.2 : suppression codes

**Comment by SEBELIN** [comment]
Vu avec VT : Pour "AI non entérinée" le SI-SdO envoie le statut 40 "Notification lue".
