### ISSUE TITLE
Ressource Consent : compléter la spec et vérifier le code utilisé

### ISSUE THREAD

**Issue by jguihot** [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation#32]
## Description du problème
Ajouter policyRule dans la spec (présent dans l'exemple) => plus d'actu avec l'IG ?
Vérifier le code OPTIN utilisé => warning lors du PAT et je ne retrouve pas trace de l'origine de ce code

## Fichier•s concerné•s
IG (specs FHIR)
Ressource de conformité Consent
Exemple ?

**Comment by TristanKEREVAL** [comment]
https://terminology.hl7.org/5.0.0/CodeSystem-v3-ActCode.html

**Comment by TristanKEREVAL** [comment]
On peut pas faire apparaitre l'élément dans la spec si on le contraint pas, il apparait dans l'onglet snapshot de la spec 
![image](https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/assets/122813625/26ea3b3f-02b1-4dc0-a6ef-0cc213b027ec)

**Comment by jguihot** [comment]
@TristanKEREVAL , il semble manquer des choses dans notre SD par rapport à la ressource FHIR. le policyRule ou le policy est rendu obligatoire par les règles de gestion sur la ressource
![image](https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/assets/135017301/66c20c87-d31e-47dd-a8cb-fb75902f4868)

**Comment by TristanKEREVAL** [comment]
Elles apparaissent bien dans la vue "All" : 


![Image](https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/assets/122813625/4080c38f-0945-4d79-a821-e74e1d241003)



![Image](https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/assets/122813625/218a405c-80bc-4bf0-96b4-5c3ee6b02d7e)

**Comment by jguihot** [comment]
Le valueSet vers lequel pointe la doc FHIR est le suivant : https://hl7.org/fhir/R4/valueset-consent-policy.html

Ne vaut-il pas mieux se fier à ce valueSet ? Si oui, il ne contient pas la valeur OPTIN. 

Je n'arrive pas à remettre la main sur la doc initiale à partir de laquelle nous avons construit l'exemple. Je suis pourtant certaine de ne pas avoir eu à choisir parmi 200 codes, il doit donc bien exister une version réduite quelque part !

**Comment by jguihot** [comment]
Quoi qu'il arrive, la structureDef sera à faire évoluer parce que nous figeons la valeur du policyRule.

**Comment by TristanKEREVAL** [comment]
Le JDV bindé est en "extensible" donc on peut prendre dans ce JDV ou alors en prendre un issue d'autre part si ce qu'on veut transmettre n''est pas dans ce premier.

**Comment by jguihot** [comment]
@nriss , je poursuis l'échange sur l'issue dédiée, plus facile à suivre que la PR.

Ma problématique de base sur la ressource Consent, c'est que l'exemple pointe vers le valueSet http://terminology.hl7.org/CodeSystem/v3-ActCode, alors que la spec FHIR actuelle pointe sur le valueSet http://hl7.org/fhir/ValueSet/consent-policy (https://hl7.org/fhir/R4/consent.html)
Je suis persuadée que, lorsque nous avons construit l'exemple il y avait une doc qui mentionnait le premier valueSet, avec un nombre restreint de code proposé (dont OPTIN) mais je n'arrive plus à remettre la main dessus.

Sans historique de ce choix, j'aurais tendance à revenir au valueSet mentionné dans la spec FHIR. Si nous faisons ça, il faudra en revanche utiliser un autre code car le code OPTIN n'est pas existant dans ce valueSet.

Nous n'avons pas besoin de cette donnée policyRule, elle est imposée par une règle de gestion dans la ressource Consent. Comment choisir un code dans cette foultitude de code ?

![Image](https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/assets/135017301/91e7ca7f-4fc6-4a9e-bcb0-572df032b04c)
