### ISSUE TITLE
DocumentReference : modifier la RC pour contourner les contraintes imposées par le paramètre _elements

### ISSUE THREAD

**Issue by jguihot** [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation#33]
## Description du problème
Le _elements=id limite les paramètres facultatifs à retourner, mais impose quand même de renseigner les données obligatoires. Donc le contenu (attachment). 

## Fichier•s concerné•s
Ig (spec Fhir)
Ressource de conformité
Exemples

## Solution proposée
Rendre obligatoire l'attribut "title" en proposant 2 titres distincts en fonction du type de document CDA.
Dans le bundle, le title de l'élément attachment sera remonté avec l'id. Plus d'erreur

Voir CR du 27/11/2023 11:36

**Comment by TristanKEREVAL** [comment]
Pour vérifier le contenu du titre, on peut mettre une règle de gestion et un short sur l'attribut

**Comment by SEBELIN** [comment]
L’objectif du flux 1.2 est de transmettre les id(s) des ressources DocumentReference consultables dans le flux 1.3.

La contrainte FHIR est de transmettre dans ce flux les éléments obligatoires de la ressource DocumentReference en particulier l’objet attachment.

Rendre obligatoire title dans attachment de la ressource DocumentReference est une très bonne solution où on répond à notre besoin et on est conforme à FHIR.

Si le flux 1.3 n’existait pas effectivement on devrait imposer les data dans attachment. Comme on maintient les 2 flux 1.2 et 1.,3 il n’est pas nécessaire d’imposer les data à ce stade.

**Comment by jguihot** [comment]
@SEBELIN , la solution du title a été validée avec les éditeurs, nous étions donc d'accord sur la marche à suivre sur ce point.

Pour ce qui est de notre suggestion elle est indépendante. Imposer le data dans une règle de gestion, et non pas par cardinalité, ne fera remonter l'information que dans le flux 1.4. Testé par @TristanKEREVAL, il n'y a pas d'erreur remontée dans le flux 1.2 avec cette gestion, et le CDA ne remontera pas dans le flux 1.2, seul le title sera remonté.

**Comment by SEBELIN** [comment]
Je ne dis pas le contraire concernant le title

dans le flux 1.4 ok pour imposer la présence du data par une règle de gestion mais pas dans le flux 1.2

**Comment by SEBELIN** [comment]
je valide les titles choisit par Tristan

**Comment by jguihot** [comment]
@TristanKEREVAL , revoir la contrainte appliquée sur la mauvaise ressource (SDO au lieu de ESMS) = > voir commentaire sur la PR

**Comment by jguihot** [comment]
@TristanKEREVAL , retour PR non traité et nous n'attendons pas de retour ni de l'ANS, ni de la CNSA => à prendre en compte

**Comment by jguihot** [comment]
PR#103 à corriger :
"severity": "warning".
"human": "Le transport des données est obligatoire lorsque la ressource complète est transportée, le champs data doit être rempli"

Liée à l'issue https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/issues/33. Imposer un niveau "erreur" entrainerait une erreur visible lors du test du flux 1.2 (Bundle) qui ne transportera que le title et pas le data. Niveau warning uniquement. Vu et validé en réunion avec l'ANS

Originally posted by @jguihot in https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/pull/103#discussion_r1467457216

**Comment by TristanKEREVAL** [comment]
Passage de error à warning

**Comment by jguihot** [comment]
Manque l'adaptation suggéré du
