### ISSUE TITLE
Ressource Task : revoir la nomenclature ModePriseEnCharge

### ISSUE THREAD

**Issue by jguihot** [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation#35]
## Description du problème
Nomenclature ModePriseCharge => doit-on utiliser les mêmes codes restreints que ceux identifiés dans le CDA ?
Manque l'url dans la SD

## Fichier•s concerné•s
Ig (spec technique)
Ressource Task
Exemples

## Solution proposée
Mettre en cohérence ressource FHIR et document CDA

**Comment by jguihot** [comment]
@SEBELIN , nous attendions un retour sur cette question, des info ?

**Comment by SEBELIN** [comment]
La mise en cohérence de la ressource FHIR Task doit se faire à partir du CDA.

**Comment by TristanKEREVAL** [comment]
Modification de l'url dans la SD : https://mos.esante.gouv.fr/NOS/JDV_XXX-ModePriseEnCharge/

**Comment by TristanKEREVAL** [comment]
Ajout d'un URL temporaire dans l'exemple : https://mos.esante.gouv.fr/NOS/TRE_R213-ModePriseEnCharge/FHIR/TRE-R213-ModePriseEnCharge

**Comment by jguihot** [comment]
OK dans l'exemple Task, KO dans l'exemple bundle

**Comment by jguihot** [comment]
A priori sujet pas traité dans le commit qui concerne les évol de la nomenclature TypeDroitPrestation

URL NOS à intégrer dans la SD.
Manque la contrainte sur les codes à utiliser:
Codes à utiliser et leur équivalence dans la nomenclature CNSA

- Code 46 « Hébergement (accueil jour et nuit) » = Internat (1)
- Code 47 « Accueil de jour » = externat (2), semi-internat (3) ou accueil de jour (6)
- Code 48 "Accueil de nuit » = Accueil de nuit (4)

Remarque : Pas de correspondance pour Centre d'accueil familial spécialisé (5)

**Comment by jguihot** [comment]
corrigé dans le commit [Task - fix URL ModePriseCharge](https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/pull/49/commits/4c423354884dfd48518bc2536d9d88075caad313)
