### ISSUE TITLE
Ressource Task : revoir la nomenclature typeDroitPrestation

### ISSUE THREAD

**Issue by jguihot** [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation#36]
## Description du problème

Nomenclature typeDroitPrestation à revoir. Pas d'URL. CodeAbleConcept mais juste displayname

## Fichier•s concerné•s

Ig (spec FHIR)
Ressource de conformité
Exemples

**Comment by TristanKEREVAL** [comment]
Modiication URL, ajout d'un URL temporaire dans les SD et les exemples et ajout d'une value temporaire dans l'exemple

**Comment by jguihot** [comment]
code et display utilisés ne sont pas issus de la nomenclature CNSA

**Comment by jguihot** [comment]
@TristanKEREVAL , cette nomenclature figure dans l'annexe de la CNSA. Tu peux par exemple utiliser @code = 1.1 et @display = AAH L.821-1

**Comment by jguihot** [comment]
Pas reporté sur le Bundle
