### ISSUE TITLE
Flux 5  - simplification - suppression des flux 5.3 et 5.4 et suppression _elements

### ISSUE THREAD

**Issue by jguihot** [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation#41]
## Description du problème
Le _elements=id limite les paramètres facultatifs à retourner, mais impose quand même de renseigner les données obligatoires, soit 5 données input. Nécessite soit de trouver un contournement, soit de simplifier les flux

## Fichier•s concerné•s
Ig (spec Fhir)
Ressource de conformité
Exemples

## Solution proposée
simplifier les flux en supprimant les flux 5.3 et 5.4 pour remonter directement dans le flux 5.2 les éléments obligatoires. A reboucler avec VT et les éditeurs de DUI => Validée avec ANS et VT

**Comment by jguihot** [comment]
Le _elements=id limite les paramètres facultatifs à retourner, mais impose quand même de renseigner les données obligatoires. Donc le contenu (attachment).

Fichier•s concerné•s
Ig (spec Fhir)
Ressource de conformité
Exemples

Solution proposée
Rendre obligatoire l'attribut "title" en proposant 2 titres distincts en fonction du type de document CDA.
Dans le bundle, le title de l'élément attachment sera remonté avec l'id. Plus d'erreur

Voir CR du 27/11/2023 11:36

**Comment by TristanKEREVAL** [comment]
L'ajout de la règle de gestion contourne ce problème

**Comment by jguihot** [comment]
Vu avec @nriss, @M-Priour, @SEBELIN, maintien de la remontée des éléments obligatoires de la ressource task dans le flux 5.2. 
Solution préconisée : simplifier les flux en supprimant les flux 5.3 et 5.4 pour remonter directement dans le flux 5.2 les éléments obligatoires. A reboucler avec VT et les éditeurs de DUI

**Comment by TristanKEREVAL** [comment]
> L'ajout de la règle de gestion contourne ce problème

Suppression de cette règle et les cardinalités sont rétablies

**Comment by jguihot** [comment]
@SEBELIN , point à prévoir avec VT et les éditeurs, pour préconiser une simplification des flux

**Comment by jguihot** [comment]
Validé avec VT le 19/01 : simplification du flux 5
