### ISSUE TITLE
Flux 1 et 5 : limite temporelle de requête à fixer

### ISSUE THREAD

**Issue by jguihot** [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation#43]
## Description du problème
VT ne pourrait pas assumer une recherche sur une durée trop important.

## Fichier•s concerné•s

requêtes des flux 1 et 5

## Solution proposée
Ajouter une préconisation textuelle dans les specs pour préciser une préconisation journalière et exceptionnelle pas au delà de 30 jours (à confirmer par l'ANS)
Etudier la possibilité de fixer une limite temporelle dans la requête (_lastUpdated)

**Comment by jguihot** [comment]
Confirmation de @SEBELIN sur les limites temporelles à fixer : 'Nous partons pour un cas nominal avec une fréquence de recherche  J-1. Le cas exceptionnel serait gérer par VT pour une 1ere connexion à VT d’un DUI (avec une profondeur de 30j)."

Note à ajouter dans les specs

**Comment by jguihot** [comment]
@KerJac35 , qu'en est-il de la possibilité de fixer une limite temporelle dans la requête ?

**Comment by jguihot** [comment]
Autre remarque : le texte n'a été ajouté que sur le flux 1 et pas le flux 5

**Comment by jguihot** [comment]
Ajout OK et uniformisation du texte

**Comment by jguihot** [comment]
@KerJac35 , retour sur la possibilité de fixer une limite temporelle à tracer dans cette issue

**Comment by KerJac35** [comment]
Pour moi, il vaut mieux conserver la gestion de cette limite temporelle au niveau de VT. On pourrait très bien créer et définir un nouveau paramètre de recherche mais ça me semble peu pertinent car cela voudrait dire que c'est le client qui, en interrogeant le serveur, se fixe une limite lui-même. 

Comme convenu, nous avons rajouté une préconisation textuelle pour les flux 1 et 5 au niveau du paramètre de recherche "lastUdated", la gestion de cette limite (vérification que le client ne la dépasse pas) reste cependant côté serveur.

**Comment by jguihot** [comment]
Vu avec VT et discuté avec @SEBELIN , gestion effectivement conservée coté VT. Ajouté également dans le référentiel fonctionnel. L'ANS a proposé un système de pénalité pour les éditeurs qui ne respecteraient pas cette limite.
