### ISSUE TITLE
Correction TRE dans profil sdo_task

### ISSUE THREAD

**Issue by TristanKEREVAL** [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation#45]
## Description du problème
Il y a des bindings vers des TRE au sein du profil, il faut mettre des JDV à la place
## Fichier•s concerné•s
StructureDefinition-sdo-task.json

## Solution proposée
Remplacer ces URL's de TRE pars de URL's de JDV

**Comment by jguihot** [comment]
traité dans l'issue #55
