### ISSUE TITLE
Contenu dossier - id document - Modifier la gestion de l'ID suivant les préconisations du CI-SIS

### ISSUE THREAD

**Issue by jguihot** [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation#46]
## Description du problème
L'id produit pour le document ne suit pas les préconisations CI-SIS. Le volet TDD évolue pour se caler sur le modèle TDDUI

## Solution proposée
Reporter le fonctionnement TDDUI / TDD

"Identifiant unique du document
•	@root = racine d'OID commune aux instances des documents d'une structure émettrice
Il est recommandé de générer une racine d'OID pour chaque structure, à partir du générateur https://www.uuidgenerator.net/version1.
•	@extension = valeur d’un identifiant unique attribué par le système d’information émetteur. Il permet d'identifier chaque instance et version des documents."

**Comment by jguihot** [comment]
@SEBELIN , pourras-tu confirmer que ce besoin est également à reporter sur ESMS ? Le fonctionnements suivait la même logique que TDD et semble bancal avec le nouveau fonctionnement en double identifiant

**Comment by SEBELIN** [comment]
je confirme
en rapportant ce qui a été mis sur TDD pour 
@extension = valeur de l'identifiant unique du document propre à la structure émettrice permettant d'identifier de façon unique chaque instance et version des documents

**Comment by jguihot** [comment]
@SEBELIN , j'ai opté pour un compromis entre ta formulation et la mienne. extension n'est pas l'identifiant unique du document. C'est le root + extension qui l'est.

**Comment by jguihot** [comment]
Exemples pas mis à jour
