### ISSUE TITLE
Fichiers zip erronés

### ISSUE THREAD

**Issue by KerJac35** [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation#48]
## Description du problème

Il y a quelques problèmes concernant les liens vers les fichiers zip téléchargeables : 
1) Dans téléchargement et usage :
      - XML exemple qui contient des .ttl et des structureDef
      - JSON exemple qui contient des structureDef
2) Ressources CDA
       - En cliquant sur "Exemples CDA", le fichier téléchargé contient les schematrons

## Fichier•s concerné•s

IG (Téléchargement et usage + Ressources CDA)

## Solution proposée

Corrections des fichiers zip et des problèmes de liens

**Comment by jguihot** [comment]
@KerJac35 , update sur le statut de cette tâche ?

**Comment by jguihot** [comment]
@nriss , nous avons des soucis de cohérence du contenu des zip de la page download (voir point 1 de la description de cette issue) J'ignore comment son générés ces zip, mais nous avons a priori le même soucis de cohérence sur l'IG TDDUI. Est-ce un sujet qui t'évoque quelque chose ?

**Comment by nriss** [comment]
Hello :)
Effectivement le lien des exemples ttl a l'air erroné
Pour les exemples c'est étrange, ça a le même comportement côté us core : https://hl7.org/fhir/us/core/STU5/downloads.html

**Comment by jguihot** [comment]
Diantre... Et pour les exemples xml je vois ça sur tous les IG ANS que j'ai regardé !

**Comment by jguihot** [comment]
![image](https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/assets/135017301/77a72ca7-38c7-4ed7-bda0-e9d56e399911)
Du coup je pense que non seulement le lien est erroné pour les exemples xml, mais en plus le zip turtle est manquant dans la liste des zip téléchargeable

**Comment by nriss** [comment]
Vous connaissez des cas d'usage ou turtle est utilisé ? Je pense qu'on peut supprimer le lien

Merci pour avoir identifié le problème en tout cas

**Comment by jguihot** [comment]
Personnellement non. Nous ne travaillions qu'en json et xml avant de passer aux IG, ça semblait convenir aux éditeurs.

J'entends de ton précédent commentaire que ces modif sont plutôt gérées de ton coté, pas à notre main ?

**Comment by jguihot** [comment]
ttl supprimés et liens vers les xml modifié (ttl remplacé par xml)
Pas de solution pour faire en sorte que les structureDef n'apparaissent pas dans les zip

**Comment by nriss** [comment]
@sdemeyANS @M-Priour pour info
