### ISSUE TITLE
Tests - Supprimer l'onglet

### ISSUE THREAD

**Issue by jguihot** [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation#57]
## Description du problème
Onglet par défaut dans les modèles IG ANS et pourtant non présent dans d'autres IG (PDSm, TDDUI,...)

Difficile à lire. 
La référence aux validateurs "ici" n'est que peu compréhensible par l'utilisateur, et obscure pour le développeur = risque d'oubli de mise à jour.
Les liens vers les résultats de tests du projectathon ne sont pas adaptés au volet
Le lien vers le référencement Ségur devrait être adapté au volet
La doc vers les modop Gazelle devrait être remplacée par les ppt de présentation spécifiques au volet

Manque les simulateurs, recap, jeux de tests et modop

## Solution proposée
Supprimer pour l'instant cet onglet en attendant de prévoir un onglet "outillage" plus adapté au volet et mieux structuré

**Comment by jguihot** [comment]
@nriss , @SEBELIN , auriez-vous un avis sur la question ?
Les informations "tests" sont mises en évidence avec un onglet dédié alors que le contenu ne me semble pas approprié au volet. Je serais donc d'avis de le supprimer pour l'instant et de prévoir un onglet plus clair et mieux détaillé pour de prochaines versions

**Comment by nriss** [comment]
L'onglet tests a été supprimé pour le mettre dans l'IG documentation, pour éviter d'avoir à maintenir cette page partout. Ok pour le supprimer :)

Cf exemple : https://ansforge.github.io/IG-fhir-mesures-de-sante/ig/main/

**Comment by jguihot** [comment]
Oh, good to know ! 
Je pense qu'à terme il faudra en ajouter un pour toute la doc spécifique au volet, les récapitulatif de validateurs, de simulateurs, les modop,... Mais pas sur ce format du coup
