### ISSUE TITLE
RC - passer les RC en FSH

### ISSUE THREAD

**Issue by jguihot** [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation#67]
## Description du problème
Les ressources actuelles étaient initialement en fomat JSON. Importées en l'état dans l'IG.
Manque une arborescence FSH attendue dans l'IG. Nécessite de lancer la commande sushi avant chaque _genonce + génère des warning lors des commit

## Fichier•s concerné•s
ressources de conformité FHIR

## Solution proposée
Passer en FSH

**Comment by TristanKEREVAL** [comment]
Récap des différences repérées entre les JSONs originaux et ceux générés par FSH : 

- Ordonnancement des attributs
- Création d'une contrainte de cardinalité minimale sur les attributs étant discriminateur d'un slicing (ex avec le input.type.text dans la SD SDOTask
- Ajout d'un attribut "Source" sur les définitions et les appels des règles de gestions
- Ajout de plusieurs extensions à la ressource "StructureDefinition" : extension": [
    {
      "url": "http://hl7.org/fhir/StructureDefinition/structuredefinition-category",
      "valueString": "Base.Workflow"
    },
    {
      "url": "http://hl7.org/fhir/StructureDefinition/structuredefinition-security-category",
      "valueCode": "not-classified"
    }
  ],
- Ajout d'un mapping : "mapping": [
    {
      "identity": "workflow",
      "uri": "http://hl7.org/fhir/workflow",
      "name": "Workflow Pattern"
    },
    {
      "identity": "rim",
      "uri": "http://hl7.org/v3",
      "name": "RIM Mapping"
    },
    {
      "identity": "w5",
      "uri": "http://hl7.org/fhir/fivews",
      "name": "FiveWs Pattern Mapping"
    },
    {
      "identity": "v2",
      "uri": "http://hl7.org/v2",
      "name": "HL7 v2 Mapping"
    }
  ],
