### ISSUE TITLE
Structure - Ressources FHIR - séparer ressources et exemples

### ISSUE THREAD

**Issue by jguihot** [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation#74]
## Demande de Nicolas Riss : 

je propose de créer un dossier example pour séparer profils et exemples

_Originally posted by @nriss in https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/pull/49#discussion_r1452228098_

## Remarque
Demande plus d'actualité si passage en FSH ?

**Comment by nriss** [comment]
Je pense qu'en FSH, on peut également créer différents dossiers : profile, example, ...

**Comment by jguihot** [comment]
Effectivement, c'est pourquoi je relie cette demande avec l'issue #67. Nous pourrons revoir la structure des dossiers lors du passage des SD en FSH

**Comment by jguihot** [comment]
traité dans la PR #166
