### ISSUE TITLE
Spec fonctionnelle - Mettre à jour la description des actions pour le flux 4 (chapitre 3.3)

### ISSUE THREAD

**Issue by jguihot** [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation#89]
## Description du problème
La description des actions est centrée sur l'entrée d'un usager en ESMS or la description du flux a évolué pour englober le transfert de tous les statuts d'un PO.

## Fichier•s concerné•s
PDF spec fonctionnelles
Sans impact sur la ST

## Solution proposée
Mettre à jour la description pour se raccrocher au diagramme

**Comment by SEBELIN** [comment]
Changement du diagramme et du tableau des descriptions 

[CISIS-SPECIFICATIONS_FONCTIONNELLES_SI-ESMS_v2.5-sans-marques.pdf](https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/files/14053511/CISIS-SPECIFICATIONS_FONCTIONNELLES_SI-ESMS_v2.5-sans-marques.pdf)

= suppression action "Informer de l'entrée en ESMS "
