### ISSUE TITLE
RC - revoir la structure pour séparer les éléments de description de ceux de contraintes

### ISSUE THREAD

**Issue by jguihot** [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation#96]
## Problèmes rencontrés

Les descriptions et contraintes appliquées aux StructureDefinition des spécifications Word ont été passé dans les éléments short des fichiers Json. Structure à revoir pour faire ressortir les contraintes et se rapprocher du format des structuresDef PSDm. Etudier notamment l'utilisation d'invariants.

ex: DocumentReference (_Originally posted by @jguihot in https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/pull/49#discussion_r1443225957_)
Je clarifierais qu'il s'agit d'une contrainte en suivant le modèle PDSm et en ajoutant le texte dans l'attribut "human", précédé d'une key type constr-bind-identifierLabel

ex: DocumentReference (_Originally posted by @jguihot in https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/pull/49#discussion_r1443251002_)
manque le lien cliquable vers  la nomenclature LOINC.
Revoir la présentation, il s'agit ici d'un binding. Le short ne me paraît pas adapté. 
Utiliser l'élément binding (avec strength required) et ajouter un commentaire avec les valeurs possibles associé à une clé "constr-bind-type" (voir https://interop.esante.gouv.fr/ig/fhir/pdsm/3.0.1/StructureDefinition-pdsm-simplified-publish.html). Pas nécessaire de spécifier le display (et même non recommandé en cas d'évolution de la nomenclature)

ex : SDOTask (_Originally posted by @jguihot in https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/pull/49#discussion_r1443287676_)
idNat_Struct : Le texte actuel aurait plus sa place dans une contrainte. Le texte mentionné dans mon précédent commentaire en revanche aurait sa place dans le short

Note : ce ne sont que quelques exemples parmi les travaux à prévoir
            

## Fichiers impactés
StructureDef JSON (à traiter en passant en FSH)

**Comment by jguihot** [comment]
Vu avec @nriss , pas de contrainte à prévoir pour idNat_Struct. La contrainte de structure figure en format texte sur d'autres IG, pas d'expression possible pour ce format

**Comment by jguihot** [comment]
@TristanKEREVAL , vu ensemble, la gestion des identifiants peut se faire par slicing, plus simple et plus propre à mettre en place qu'une règle de gestion. Le short de l'élément parent pourrait être "identifiant métier (idDecision) et technique (idNat_decision) de la décision d'orientation"

**Comment by TristanKEREVAL** [comment]
@nriss Petite question, est ce que t'as déjà vu ce genre de message dans le QA : 


![Image](https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/assets/122813625/b84e0709-f38e-4d9e-b87c-6b023e89925e)

On pensait que c'était du au fait que l'attribut évalué était répétable mais après vérification ça change rien même si on fixe la cardinalité de l'élément.
Est ce que t'aurais une idée de comment fix ça ?

**Comment by nriss** [comment]
Je pense qu'il faut tester l'existence comme défini ici : https://hl7.org/fhirpath/N1/#existscriteria-expression-boolean

Qu'un élément coding existe où le code est 57...

**Comment by jguihot** [comment]
@TristanKEREVAL , vu ensemble, la préconisation de @nriss solutionne effectivement le warning. 
En revanche reste à tester si elle fonctionne, même sans forcer la cardinalité max à 1 pour le coding (ce qui devrait normalement fonctionner). Si oui, supprimer les max à 1. Si non, réfléchir à uniformiser la cardinalité max sur l'ensemble des codeAbleConcept utilisés

**Comment by jguihot** [comment]
@TristanKEREVAL , vu ensemble, pour l'élément type, dans la mesure où nous fixons la valeur, il reste effectivement pertinent de figer le coding à max 1, aucune autre valeur n'étant permise.

**Comment by TristanKEREVAL** [comment]
> @TristanKEREVAL , vu ensemble, pour l'élément type, dans la mesure où nous fixons la valeur, il reste effectivement pertinent de figer le coding à max 1, aucune autre valeur n'étant permise.

Contrainte appliquée sur les éléments évalués par une règle de gestion  : 
ESMSDocumentReference.type.coding passe à 1..1 pour évitr plusieurs coding sous un CodeableConcept
SDOTask.input[modePriseCharge].coding passe à 1..1 pour éviter plusieurs coding sous un codeableConcept
