### ISSUE TITLE
DocumentReference - Contrainte DocumentReference.type à reporter sur ESMS au lieu de SDO

### ISSUE THREAD

**Issue by jguihot** [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation#97]
## Description du problème
Actuellement, sur la branche presta-98, la description de la contrainte associée au type du documentReference est portée dans le short du DocumentReference SDO. Or le type n'est pas à renseigner sur cette ressource. 
Le short est à reporter sur la ressource DocumentReference ESMS

## Fichier•s concerné•s
StructureDefinition-esms-document-reference.json
StructureDefinition-sdo-document-reference.json

**Comment by jguihot** [comment]
PR#103 à corriger : 
              "severity": "warning". 
"human": "Le transport des données est obligatoire lorsque la ressource complète est transportée, le champs data doit être rempli"

Liée à l'issue [#33](https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/issues/33). Imposer un niveau "erreur" entrainerait une erreur visible lors du test du flux 1.2 (Bundle) qui ne transportera que le title et pas le data. Niveau warning uniquement. Vu et validé en réunion avec l'ANS

_Originally posted by @jguihot in https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/pull/103#discussion_r1467457216_

**Comment by jguihot** [comment]
PR https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/pull/103 à corriger :
à reporter sur la ressource ESMS !
Voir issue #https://github.com/orgs/ansforge/projects/23/views/6?sliceBy%5Bvalue%5D=TristanKEREVAL&pane=issue&itemId=51174667

Originally posted by @jguihot in https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/pull/103#discussion_r1467469582

**Comment by jguihot** [comment]
PR https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/pull/103 à corriger :
à reporter sur la ressource ESMS !
Voir issue #https://github.com/orgs/ansforge/projects/23/views/6?sliceBy%5Bvalue%5D=TristanKEREVAL&pane=issue&itemId=51174667

Originally posted by @jguihot in https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/pull/103#discussion_r1467469582

**Comment by TristanKEREVAL** [comment]
short ajouté dans la ressource esms-docurefernce dans la pr #103
