### ISSUE TITLE
SD - SDOTask - corriger certaines anomalies

### ISSUE THREAD

**Issue by jguihot** [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation#98]
## Description du problème

- [x] idNat_Struct (_Originally posted by @jguihot in https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/pull/49#discussion_r1443287676_)

Manque le début de la description : "Identifiant de l'ESMS accueillant l'individu en situation de handicap. "

- [x] MotifESMS (_Originally posted by @jguihot in https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/pull/49#discussion_r1443294747_)

Manque la contrainte "Motifs obligatoires pour certains statuts suivant la table : [ASS_A32-StatutMotifPersonnePriseCharge](https://mos.esante.gouv.fr/NOS/ASS_A32-StatutMotifPersonnePriseCharge/)"
Ajouter un lien vers l'URL de la table d'association
(voir issue #24)

- [x] NomUnite (_Originally posted by @jguihot in https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/pull/49#discussion_r1443307434_)

Manque toute la définition du nom de l'unité:
'Identifiant de l'unité qui correspond à l’identifiant de l'organisation interne, unique et persistant au niveau national, et généré par une instance régionale du ROR (pour plus de précision, voir la spécification « ANS ROR - Modèle Exposition"

## Fichier•s concerné•s
StructureDefinition-sdo-task.json

**Comment by TristanKEREVAL** [comment]
@jguihot pour le nomESMS, la description est celle de l'id non ? C'est une erreur qu'on a déjà identifié

**Comment by jguihot** [comment]
@TristanKEREVAL , la description est effectivement celle de l'unité. Mais elle est tout de même manquante dans la structureDef. Il est actuellement décrit "Permet de définir l’identifiant de l’unité"
